# Generated by Django 3.1.5 on 2021-02-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_auto_20210131_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuesDetail',
            fields=[
                ('Issue_Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('DescriptionShort', models.TextField()),
                ('MedicalCondition', models.TextField()),
                ('Name', models.CharField(max_length=200)),
                ('ProfName', models.CharField(max_length=200)),
                ('TreatmentDescription', models.TextField()),
            ],
        ),
    ]
